name: Update Google Sheet

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:  # Allows manual triggering

concurrency: 
  group: database-update

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests pandas gspread oauth2client

    - name: Update Google Sheet
      env:
        SHEET_ID: ${{ secrets.SHEET_ID }}
        GOOGLE_API_KEYS: ${{ secrets.GOOGLE_API_KEYS }}
      run: python src/scripts/update_google_sheet.py

    - name: Verify changes
      run: |
        echo "Checking for changes in data files..."
        git status

    - name: Commit and push changes
      run: |
        git config --global user.name 'JamesAlfonse'
        git config --global user.email 'jamesalfonse@gmail.com'
        git add data/company_tickers_exchange.json data/Full_Database_Backend.db
        git commit -m "Updated Google Sheets"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
